September 2026
01:00    08:00    Common Time (1-min) (no switching)
08:00    11:00    Common Time (1-min) (normalsound) [ALL] (see Note A)
11:00    20:00    Discretionary Time
20:00    29:00    Common Time (1-min)
29:00    30:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  21d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h

# Notes:

Note A: This time covers the 'normalsound' Common Time
request (Thomas). All radars are requested to run the *REVISED*
'normalsound' radar control program for a full 72 hours.
