August 2026
01:00    05:00    Common Time (1-min) (no switching)
05:00    08:00    Common Time (1-min) (normalsound) [ALL] (see Note A)
08:00    17:00    Discretionary Time (See Note B)
17:00    27:00    Common Time (1-min)
27:00    31:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  22d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h

# Notes:

Note A: This time covers the 'normalsound' Common Time
request (Thomas). All radars are requested to run the *REVISED*
'normalsound' radar control program for a full 72 hours.

Note B: This time covers the eclipse Discretionary Time
request (Thomas).
