November 2026
01:00    02:19    Common Time (1-min) (no switching)
02:19    11:19    Discretionary Time (see Note A)
11:19    17:02    Special Time (rocketsound) [HAN ICE] (see Note A)
17:02    23:00    Common Time (1-min)
23:00    26:00    Common Time (1-min) (normalsound) [ALL] (see Note B)
26:00    30:24    Common Time (1-min)

# Total Common Time (1-min):  15d  17h
# Total Discretionary Time:  9d  0h
# Total Special Time:  5d  7h

# Notes:

Note A: This time covers the SYSTER rocket request (Wright).
The Hankasalmi (HAN) and Iceland East (ICE) radars are requested
to run the special 'rocketsound' control program during the launch
window (19-02 UT) each day.

Note B: This time covers the 'normalsound' Common Time
request (Thomas). All radars are requested to run the *REVISED*
'normalsound' radar control program for a full 72 hours.
