May 2026
01:00    04:00    Common Time (1-min) (no switching)
04:00    07:00    Common Time (1-min) (normalsound) [ALL] (see Note A)
07:00    16:00    Discretionary Time
16:00    18:00    Common Time (1-min) (interleavescan) [ALL] (see Note B)
18:00    24:00    Common Time (1-min) (interleavescan) [ALL] (see Notes B and C)
24:00    25:00    Common Time (1-min) (see Note C)
25:00    31:24    Common Time (1-min)

# Total Common Time (1-min):  22d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h

# Notes:

Note A: This time covers the 'normalsound' Common Time
request (Thomas). All radars are requested to run the *REVISED*
'normalsound' radar control program for a full 72 hours.

Note B: This is a spacecraft working group request to support the
ARASE/ERG mission. All radars should run interleaved_normalscan
(a full scan of at least 16 beams with a non-sequential manner that
interleaves the beam number, with a scan time of 1-min).

Note C: This time covers the JHU/APL request to support the "ITSI"
HF receiver deployed to the International Space Station (Chartier).
All mid-latitude radars are requested to operate in one of two
specified bands:  10680-10880 kHz and 15450-15650 kHz,
respectively. Full FOV modes are also requested where possible.
