March 2019
01:00    03:00    Common Time (1-min) (no switching)
03:00    06:00    Discretionary Time
06:00    12:00    Common Time (1-min) (no switching)
12:00    15:00    Discretionary Time
15:00    21:00    Common Time (1-min)
21:00    24:00    Discretionary Time
24:00    29:00    Common Time (1-min)
29:00    31:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  22d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
