June 2019
01:00    10:00    Common Time (1-min) (no switching)
10:00    13:00    Discretionary Time
13:00    15:00    Common Time (1-min) (no switching)
15:00    17:00    Common Time (1-min)
17:00    20:00    Discretionary Time
20:00    24:00    Common Time (1-min)
24:00    27:00    Discretionary Time
27:00    30:24    Common Time (1-min)

# Total Common Time (1-min):  21d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
