May 2019
01:00    07:00    Common Time (1-min) (no switching)
07:00    10:00    Discretionary Time
10:00    15:00    Common Time (1-min) (no switching)
15:00    18:00    Discretionary Time
18:00    21:00    Common Time (1-min)
21:00    24:00    Discretionary Time
24:00    31:24    Common Time (1-min)

# Total Common Time (1-min):  22d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
