January 2010
01:00    10:00    Discretionary Time
10:00    12:00    Common Time (1-min) (no switching)
12:00    16:00    Common Time (1-min)
16:00    20:12    Common Time (THEMIS)
20:12    23:00    Common Time (1-min)
23:00    25:12    Common Time (THEMIS)
25:12    27:00    Common Time (1-min)
27:00    31:24    Common Time (THEMIS)

# Total Common Time (1-min):  10d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
# Total Common Time (THEMIS):  12d  0h
