November 2020
01:00    09:00    Common Time (1-min) (no switching)
09:00    12:00    Discretionary Time
12:00    16:00    Common Time (1-min)
16:00    19:00    Discretionary Time
19:00    23:00    Common Time (1-min)
23:00    26:00    Discretionary Time
26:00    28:00    Common Time (1-min)
28:00    30:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  21d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
