February 2020
01:00    08:00    Common Time (1-min) (no switching)
08:00    10:00    Common Time (1-min)
10:00    13:00    Discretionary Time
13:00    17:00    Common Time (1-min)
17:00    20:00    Discretionary Time
20:00    24:00    Common Time (1-min)
24:00    27:00    Discretionary Time
27:00    29:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  20d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
