January 2020
01:00    12:00    Common Time (1-min) (no switching)
12:00    13:00    Common Time (1-min)
13:00    16:00    Discretionary Time
16:00    20:00    Common Time (1-min)
20:00    23:00    Discretionary Time
23:00    27:00    Common Time (1-min)
27:00    30:00    Discretionary Time
30:00    31:24    Common Time (1-min)

# Total Common Time (1-min):  22d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
