May 2000
01:00    03:00    Common Time
03:00    07:00    Discretionary Time   (Note 1)
07:00    19:00    Common Time
19:00    24:00    Discretionary Time
24:00    28:00    Common Time
28:00    31:24    Common Time, HTR*

*HTR   : Common Program, High-Time Resolution
Note 1 : This is for Natsuo Sato's request. All of the southern hemisphere
         and CUTLASS radars are concerned. The RCP for this experiment
         should be posted soon.
