April 2000
01:00    05:00    Discretionary Time
05:00    07:00    Common Time
07:00    11:00    Discretionary Time
11:00    13:00    Common Time
13:00    14:00    Discretionary Time
14:00    17:00    Common Time
17:00    21:00    Common Time, HTR*
21:00    24:00    Common Time
24:00    27:00    Special Time       (Note 1)
27:00    30:24    Common Time

*HTR   : High-Time Resolution Common Program
Note 1 : This is for the french request. The RCP to be run is
         FTE_4204
