March 2000
01:00    05:00    Common Time
05:00    06:00    Special Time         (Note 1)
06:00    08:00    Special Time         (Note 2)
08:00    11:00    Discretionary Time
11:00    16:00    Common Time
16:00    17:00    Special Time         (Note 1)
17:00    21:00    Common Time, HTR*
21:00    22:00    Special Time         (Note 1)
22:00    26:00    Discretionary Time
26:00    27:00    Special Time         (Note 1)
27:00    29:00    Discretionary Time
29:00    31:24    Common Time

*HTR   : High-Time Resolution Common Program
Note 1 : This is for Natsuo Sato's request
Note 2 : This is for Jean-Claude Cerisier's request
