April 2022
01:00    04:00    Common Time (1-min) (no switching)
04:00    07:00    Discretionary Time
07:00    11:00    Common Time (1-min)
11:00    14:00    Discretionary Time
14:00    18:00    Common Time (1-min)
18:00    21:00    Discretionary Time
21:00    23:00    Common Time (1-min)
23:00    30:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  21d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
