June 2022
01:00    06:00    Common Time (1-min) (no switching)
06:00    09:00    Discretionary Time
09:00    13:00    Common Time (1-min)
13:00    16:00    Discretionary Time
16:00    20:00    Common Time (1-min)
20:00    23:00    Discretionary Time
23:00    25:00    Common Time (1-min)
25:00    30:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  21d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
