February 2021
01:00    08:00    Common Time (1-min) (no switching)
08:00    11:00    Discretionary Time
11:00    15:00    Common Time (1-min)
15:00    18:00    Discretionary Time
18:00    22:00    Common Time (1-min)
22:00    25:00    Discretionary Time
25:00    26:00    Common Time (1-min)
26:00    28:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  19d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
