January 2021
01:00    11:00    Common Time (1-min) (no switching)
11:00    14:00    Discretionary Time
14:00    18:00    Common Time (1-min)
18:00    21:00    Discretionary Time
21:00    25:00    Common Time (1-min)
25:00    28:00    Discretionary Time
28:00    31:00    Common Time (1-min)
31:00    31:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  22d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
