August 2021
01:00    09:00    Common Time (1-min) (no switching)
09:00    12:00    Discretionary Time
12:00    16:00    Common Time (1-min)
16:00    19:00    Discretionary Time
19:00    23:00    Common Time (1-min)
23:00    26:00    Discretionary Time
26:00    29:00    Common Time (1-min)
29:00    31:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  22d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
