April 2021
01:00    05:00    Common Time (1-min) (no switching)
05:00    08:00    Discretionary Time
08:00    12:00    Common Time (1-min)
12:00    15:00    Discretionary Time
15:00    19:00    Common Time (1-min)
19:00    22:00    Discretionary Time
22:00    24:00    Common Time (1-min)
24:00    30:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  21d  0h
# Total Discretionary Time:  9d  0h
# Total Special Time:  0d  0h
