January 2001
01:00    12:00    Common Time
12:00    21:00    Discretionary Time
21:00    26:00    Common Time (HTR 1 minute)
26:00    31:24    Common Time

Regarding the part of Discretionary Time from the 14th to
the 20th all of the radars in the northern hemisphere
[except that I have no confirmation for Stokkseyri yet]
will run in 1 minute HTR mode as much as possible. This
is in support of the PolarMax campaign.
